<?php

namespace App\Services;

use Illuminate\Support\Arr;
use Illuminate\Support\Facades\File;

class ReleaseReadinessService
{
    public function __construct(
        private ?string $basePath = null,
        private ?array $releaseConfig = null,
    ) {
        $this->basePath ??= base_path();
        $this->releaseConfig ??= config('release', []);
    }

    public function inspect(): array
    {
        $checks = [];

        foreach ($this->requiredFiles() as $file) {
            $checks[] = $this->check(
                'Required file: '.$file,
                File::isFile($this->path($file)),
                true,
                'Include this file in the release package before shipping.'
            );
        }

        foreach ($this->requiredLocationCsvs() as $file) {
            $checks[] = $this->check(
                'Required location CSV: '.$file,
                File::isFile($this->path($file)),
                true,
                'The release should include only the bootstrap/sample location CSV package.'
            );
        }

        foreach ($this->writableDirectories() as $directory) {
            $path = $this->path($directory);
            $checks[] = $this->check(
                'Writable directory exists: '.$directory,
                File::isDirectory($path),
                true,
                'Create this directory and include an empty placeholder in the release package.'
            );

            if (File::isDirectory($path)) {
                $checks[] = $this->check(
                    'Writable directory permission: '.$directory,
                    File::isWritable($path),
                    false,
                    'This directory must be writable on the customer server after upload.'
                );
            }
        }

        $checks = array_merge(
            $checks,
            $this->environmentChecks(),
            $this->exclusionChecks(),
        );

        return $checks;
    }

    public function hasCriticalFailures(?array $checks = null): bool
    {
        return collect($checks ?? $this->inspect())
            ->contains(fn (array $check) => $check['critical'] && $check['status'] === 'fail');
    }

    public function summary(?array $checks = null): array
    {
        $checks ??= $this->inspect();

        return [
            'passes' => collect($checks)->where('status', 'pass')->count(),
            'warnings' => collect($checks)->where('status', 'warning')->count(),
            'failures' => collect($checks)->where('status', 'fail')->count(),
        ];
    }

    public function requiredFiles(): array
    {
        return Arr::get($this->releaseConfig, 'required_files', []);
    }

    public function requiredLocationCsvs(): array
    {
        return Arr::get($this->releaseConfig, 'required_location_csvs', []);
    }

    public function writableDirectories(): array
    {
        return Arr::get($this->releaseConfig, 'writable_directories', []);
    }

    public function excludePatterns(): array
    {
        return Arr::get($this->releaseConfig, 'exclude_patterns', []);
    }

    private function environmentChecks(): array
    {
        $checks = [];
        $examples = [
            '.env.example' => [
                'DEPLOYMENT_MODE' => 'self_hosted',
                'INSTALLER_ENABLED' => 'true',
                'CAMPAIGN_PORTAL_API_BASE' => 'https://campaignmanager.ng/api/v2',
                'BROADCAST_CONNECTION' => 'log',
                'QUEUE_CONNECTION' => 'sync',
                'CACHE_STORE' => 'file',
                'SESSION_DRIVER' => 'file',
            ],
            '.env.production.example' => [
                'DEPLOYMENT_MODE' => 'self_hosted',
                'INSTALLER_ENABLED' => 'true',
                'CAMPAIGN_PORTAL_API_BASE' => 'https://campaignmanager.ng/api/v2',
                'BROADCAST_CONNECTION' => 'log',
                'QUEUE_CONNECTION' => 'sync',
                'CACHE_STORE' => 'file',
                'SESSION_DRIVER' => 'file',
                'APP_DEBUG' => 'false',
            ],
        ];

        foreach ($examples as $file => $expected) {
            $values = $this->readEnvExample($file);

            foreach ($expected as $key => $value) {
                $actual = $values[$key] ?? null;
                $checks[] = $this->check(
                    "{$file} default: {$key}",
                    $actual === $value,
                    true,
                    "Expected {$key}={$value} for self-hosted packaging."
                );
            }

            $checks[] = $this->check(
                "{$file} has no real APP_KEY",
                empty($values['APP_KEY'] ?? null),
                true,
                'APP_KEY must be generated by the customer installer, not shipped.'
            );
        }

        return $checks;
    }

    private function exclusionChecks(): array
    {
        $checks = [];
        $patterns = $this->excludePatterns();

        foreach (['.env', '.htaccess', 'htaccess', '*.sql', 'storage/app/installed.lock', 'public/uploads/community/photos/*', 'public/uploads/community/videos/*', 'public/uploads/member_images/*'] as $pattern) {
            $checks[] = $this->check(
                'Release exclude rule: '.$pattern,
                in_array($pattern, $patterns, true),
                true,
                'Add this path to release ZIP exclude rules.'
            );
        }

        foreach (['.env', 'storage/app/installed.lock'] as $localOnlyFile) {
            if (File::exists($this->path($localOnlyFile))) {
                $checks[] = [
                    'label' => 'Local-only file present and excluded: '.$localOnlyFile,
                    'status' => 'warning',
                    'message' => 'This file exists locally but must not be included in the release ZIP.',
                    'critical' => false,
                ];
            }
        }

        return $checks;
    }

    private function readEnvExample(string $relativePath): array
    {
        $path = $this->path($relativePath);
        if (!File::isFile($path)) {
            return [];
        }

        $values = [];
        foreach (File::lines($path) as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#') || !str_contains($line, '=')) {
                continue;
            }

            [$key, $value] = explode('=', $line, 2);
            $values[trim($key)] = trim($value, "\"'");
        }

        return $values;
    }

    private function path(string $relativePath): string
    {
        return rtrim($this->basePath, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.str_replace(['/', '\\'], DIRECTORY_SEPARATOR, $relativePath);
    }

    private function check(string $label, bool $passes, bool $critical, string $message): array
    {
        return [
            'label' => $label,
            'status' => $passes ? 'pass' : ($critical ? 'fail' : 'warning'),
            'message' => $passes ? 'OK' : $message,
            'critical' => $critical,
        ];
    }
}
