@extends('backend.template.backend-master')
@section('content')
<section class="content"><div class="container-fluid">
<div class="card"><div class="card-header"><h3 class="card-title">Batch {{ $batch->local_batch_reference }}</h3><form class="float-right" method="POST" action="{{ route($profileData->access_level.'.sms.batches.sync', $batch) }}">@csrf<button class="btn btn-sm btn-outline-primary"><i class="fas fa-sync mr-1"></i> Sync delivery and billing</button></form></div><div class="card-body">
    <div class="alert alert-info"><strong>Delivery and billing are separate.</strong> Failed, expired, rejected, undelivered, or DND-blocked messages are not automatically refundable. Refunds shown here come only from portal settlement evidence.</div>
    <div class="row"><div class="col-md-3"><strong>Status</strong><br>{{ str($batch->portal_status ?: $batch->status)->replace('_', ' ')->title() }}</div><div class="col-md-3"><strong>Sent by</strong><br>{{ trim(($batch->createdBy?->firstname ?? '').' '.($batch->createdBy?->lastname ?? '')) ?: 'Unknown' }}</div><div class="col-md-3"><strong>Sender / route</strong><br>{{ $batch->sender_id }} · {{ str($batch->route)->title() }}</div><div class="col-md-3"><strong>Last synced</strong><br>{{ $batch->last_synced_at?->format('d M Y H:i:s') ?: 'Not synchronized yet' }}</div></div><hr>
    <div class="row"><div class="col-md-3"><strong>Source</strong><br>{{ str($batch->source_context ?: 'unknown')->after(':')->replace('_', ' ')->title() }}</div><div class="col-md-3"><strong>Target scope</strong><br>{{ data_get($batch->target_scope_metadata, 'scope', 'Recorded audience') }}@if(data_get($batch->target_scope_metadata, 'locations'))<br><small>{{ collect(data_get($batch->target_scope_metadata, 'locations'))->map(fn($v,$k)=>$k.': '.$v)->join(', ') }}</small>@endif</div><div class="col-md-3"><strong>Recipients</strong><br>{{ number_format($batch->valid_recipient_count) }} valid · {{ number_format($batch->invalid_recipient_count) }} invalid · {{ number_format($batch->duplicate_recipient_count) }} duplicates</div><div class="col-md-3"><strong>Scheduled</strong><br>{{ data_get($batch->metadata, 'scheduled_at') ?: 'Immediate submission' }}</div></div><hr>
    <div class="row"><div class="col-md-2"><strong>Estimated</strong><br>{{ $batch->currency ?: $batch->wallet?->currency }} {{ number_format((float) $batch->estimated_amount, 2) }}</div><div class="col-md-2"><strong>Reserved</strong><br>{{ number_format((float) $batch->reserved_amount, 2) }}</div><div class="col-md-2"><strong>Debited / charged</strong><br>{{ number_format((float) $batch->debited_amount, 2) }}</div><div class="col-md-2"><strong>Refunded / reversed</strong><br>{{ number_format((float) $batch->reversed_amount, 2) }}</div><div class="col-md-2"><strong>Released pre-debit</strong><br>{{ number_format((float) $batch->released_amount, 2) }}</div><div class="col-md-2"><strong>Settlement</strong><br>{{ str($batch->settlement_status ?: 'pending')->replace('_', ' ')->title() }}</div></div>
    <hr><strong>Message</strong><div class="border rounded p-3 mt-2" style="white-space:pre-wrap">{{ $batch->message_body }}</div>
</div></div>
<div class="row"><div class="col-lg-6"><div class="card"><div class="card-header">Delivery counts</div><div class="card-body">@forelse($deliveryCounts as $label => $count)<span class="badge badge-{{ $label === 'delivered' ? 'success' : (in_array($label, ['failed','rejected','undelivered','expired']) ? 'danger' : 'secondary') }} mr-1">{{ str($label)->replace('_', ' ')->title() }} {{ number_format($count) }}</span>@empty<span class="text-muted">No delivery statuses synchronized.</span>@endforelse</div></div></div><div class="col-lg-6"><div class="card"><div class="card-header">Billing counts</div><div class="card-body">@forelse($billingCounts as $label => $count)<span class="badge badge-{{ $label === 'refunded' ? 'success' : ($label === 'billing_review_required' ? 'warning' : 'info') }} mr-1">{{ str($label)->replace('_', ' ')->title() }} {{ number_format($count) }}</span>@empty<span class="text-muted">No billing statuses synchronized.</span>@endforelse</div></div></div></div>
<div class="card"><div class="card-header">Recipient and message history</div><div class="card-body table-responsive"><table class="table table-sm table-bordered"><thead><tr><th>Recipient</th><th>Name</th><th>Delivery</th><th>Billing</th><th>Refund eligibility</th><th>Refunded</th><th>Refund reason/evidence</th><th>Charge</th><th>Last synced</th></tr></thead><tbody>
@forelse($messages as $message)<tr><td>{{ $message->recipient_phone }}</td><td>{{ $message->recipient_name ?: '—' }}</td><td><span class="badge badge-{{ $message->delivery_status === 'delivered' ? 'success' : (in_array($message->delivery_status, ['failed','rejected','undelivered','expired']) ? 'danger' : 'secondary') }}">{{ str($message->delivery_status ?: 'queued')->replace('_', ' ')->title() }}</span></td><td>@if($message->billing_review_required)<span class="badge badge-warning">Billing Review Required</span>@else<span class="badge badge-info">{{ str($message->billing_status ?: 'pending')->replace('_', ' ')->title() }}</span>@endif</td><td>{{ is_null($message->refund_eligible) ? 'Not reported' : ($message->refund_eligible ? 'Eligible by portal evidence' : 'Not eligible') }}</td><td>{{ $message->refunded ? 'Yes' : 'No' }}</td><td>{{ $message->refund_reason ?: '—' }}@if($message->refund_evidence)<br><small>{{ str($message->refund_evidence)->replace('_', ' ')->title() }}</small>@endif</td><td>{{ $message->client_charge_amount === null ? '—' : number_format((float) $message->client_charge_amount, 2) }}</td><td>{{ $message->last_synced_at?->format('d M Y H:i') ?: '—' }}</td></tr>@empty<tr><td colspan="9" class="text-center">No recipient records.</td></tr>@endforelse
</tbody></table>{{ $messages->links() }}</div></div>
</div></section>
@endsection
