@extends('backend.template.backend-master')
@section('content')
@php($form = $form ?? old())
<section class="content"><div class="container-fluid">
    @if($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if(!$senderIds->count())
        <div class="alert alert-warning">No approved sender ID is available. You may review this page, but sending is blocked. <a href="{{ route($profileData->access_level.'.sms.sender-ids') }}">Open Sender IDs</a>.</div>
    @endif
    @if(!$settings?->portal_sms_sending_enabled)<div class="alert alert-warning">SMS sending is currently disabled by a super administrator. Recipient preview and cost estimates remain available, but confirmation is blocked.</div>@endif
    <form method="POST" action="{{ route($profileData->access_level.'.sms.compose.estimate') }}" id="sms-compose-form">@csrf
    <div class="row"><div class="col-lg-8">
        <div class="card"><div class="card-header">Message</div><div class="card-body">
            <div class="form-row"><div class="form-group col-md-6"><label>Approved sender ID</label><select class="form-control" name="sender_id" required><option value="">Select sender ID</option>@foreach($senderIds as $sender)<option value="{{ $sender->sender_id }}" @selected(($form['sender_id'] ?? '') === $sender->sender_id)>{{ $sender->sender_id }}</option>@endforeach</select></div>
            <div class="form-group col-md-6"><label>Route</label><select class="form-control" name="route" required><option value="regular" @selected(($form['route'] ?? $settings?->portal_sms_default_route) === 'regular')>Regular</option><option value="priority" @selected(($form['route'] ?? $settings?->portal_sms_default_route) === 'priority')>Priority</option></select></div></div>
            <div class="form-group"><label>Message</label><textarea class="form-control" rows="6" maxlength="{{ config('portal_sms.compose.message_max_characters', 10000) }}" name="message" id="sms-message" required>{{ $form['message'] ?? '' }}</textarea><small class="text-muted"><span id="sms-char-count">0</span> characters · <span id="sms-encoding">GSM-7</span> · approximately <span id="sms-pages">1</span> SMS page(s) per recipient. The portal estimate is authoritative.</small></div>
            <div class="form-group"><label>Schedule (optional)</label><input class="form-control" type="datetime-local" name="scheduled_at" value="{{ $form['scheduled_at'] ?? '' }}"><small class="text-muted">Leave blank to submit immediately. Times use {{ config('app.timezone') }}.</small></div>
        </div></div>
        <div class="card"><div class="card-header">Recipients</div><div class="card-body">
            <div class="form-group"><label>Recipient source</label><select class="form-control" name="recipient_source" id="recipient-source">@foreach($sourceLabels as $value => $label)<option value="{{ $value }}" @selected(($form['recipient_source'] ?? 'members') === $value)>{{ $label }}</option>@endforeach</select></div>
            <div id="database-filters">
                <div class="form-row"><div class="form-group col-md-3"><label>State</label><select class="form-control scope-select" id="sms-state" name="filters[state_id]" data-selected="{{ data_get($form, 'filters.state_id') }}"><option value="">All permitted</option></select></div>
                <div class="form-group col-md-3"><label>LGA</label><select class="form-control scope-select" id="sms-lga" name="filters[lga_id]" data-selected="{{ data_get($form, 'filters.lga_id') }}"><option value="">All permitted</option></select></div>
                <div class="form-group col-md-3"><label>Ward</label><select class="form-control scope-select" id="sms-ward" name="filters[ward_id]" data-selected="{{ data_get($form, 'filters.ward_id') }}"><option value="">All permitted</option></select></div>
                <div class="form-group col-md-3"><label>Polling unit</label><select class="form-control scope-select" id="sms-pu" name="filters[polling_unit_id]" data-selected="{{ data_get($form, 'filters.polling_unit_id') }}"><option value="">All permitted</option></select></div></div>
                <div class="form-row"><div class="form-group col-md-3"><label>Access level</label><select class="form-control" name="filters[access_level]"><option value="">Any eligible level</option>@foreach($accessLevels as $value => $label)<option value="{{ $value }}" @selected(data_get($form, 'filters.access_level') === $value)>{{ $label }}</option>@endforeach</select></div>
                <div class="form-group col-md-3"><label>Account status</label><select class="form-control" name="filters[member_status]"><option value="active">Active</option><option value="all" @selected(data_get($form, 'filters.member_status') === 'all')>All</option><option value="inactive" @selected(data_get($form, 'filters.member_status') === 'inactive')>Inactive</option></select></div>
                <div class="form-group col-md-3"><label>Onboarding</label><select class="form-control" name="filters[onboarding_status]"><option value="all">All</option><option value="complete" @selected(data_get($form, 'filters.onboarding_status') === 'complete')>Complete</option><option value="incomplete" @selected(data_get($form, 'filters.onboarding_status') === 'incomplete')>Incomplete</option></select></div>
                <div class="form-group col-md-3"><label>Phone availability</label><select class="form-control" name="filters[phone_availability]"><option value="all">All</option><option value="available" @selected(data_get($form, 'filters.phone_availability') === 'available')>Has phone</option><option value="missing" @selected(data_get($form, 'filters.phone_availability') === 'missing')>Missing phone</option></select></div></div>
                <div class="form-group" id="agent-status-wrap"><label>Agent approval status</label><select class="form-control" name="filters[agent_status]"><option value="approved">Approved</option><option value="pending" @selected(data_get($form, 'filters.agent_status') === 'pending')>Pending</option><option value="suspended" @selected(data_get($form, 'filters.agent_status') === 'suspended')>Suspended</option><option value="revoked" @selected(data_get($form, 'filters.agent_status') === 'revoked')>Revoked</option><option value="rejected" @selected(data_get($form, 'filters.agent_status') === 'rejected')>Rejected</option></select></div>
            </div>
            <div class="form-group" id="manual-recipients"><label>Pasted phone numbers</label><textarea class="form-control" rows="7" name="manual_recipients" placeholder="One number per line, or separate numbers with commas">{{ $form['manual_recipients'] ?? '' }}</textarea><small class="text-muted">Accepted formats include 0XXXXXXXXXX, 234XXXXXXXXXX, and +234XXXXXXXXXX. Invalid entries are skipped and normalized duplicates are removed.</small></div>
        </div></div>
    </div><div class="col-lg-4">
        <div class="card"><div class="card-header">Charge wallet</div><div class="card-body">
            <div class="custom-control custom-radio mb-3"><input class="custom-control-input" type="radio" id="wallet-user" name="wallet_type" value="user_wallet" @checked(($form['wallet_type'] ?? 'user_wallet') === 'user_wallet')><label class="custom-control-label" for="wallet-user">My SMS wallet<br><strong>{{ $userWallet->currency }} {{ number_format((float) $userWallet->available_balance, 2) }}</strong> available</label></div>
            @if($organizationWallet)<div class="custom-control custom-radio mb-3"><input class="custom-control-input" type="radio" id="wallet-org" name="wallet_type" value="organization_wallet" @checked(($form['wallet_type'] ?? '') === 'organization_wallet')><label class="custom-control-label" for="wallet-org">Organization SMS wallet<br><strong>{{ $organizationWallet->currency }} {{ number_format((float) $organizationWallet->available_balance, 2) }}</strong> available</label></div>@endif
            <a href="{{ route($profileData->access_level.'.sms.wallet') }}">Top up, request credit, or view wallet ledger</a>
        </div></div>
        <div class="alert alert-secondary">Recipient scope is enforced again on the server during estimate and send. Provider dispatch chunk size does not impose a 100-recipient compose limit.</div>
        <button class="btn btn-primary btn-block" type="submit" @disabled(!$senderIds->count())>Preview recipients and estimate</button>
    </div></div></form>

    @isset($confirmation)
    <div class="card border-primary"><div class="card-header bg-primary"><h3 class="card-title">Confirm SMS batch</h3></div><div class="card-body">
        <div class="row"><div class="col-md-6"><dl class="row"><dt class="col-sm-5">Sender ID</dt><dd class="col-sm-7">{{ $form['sender_id'] }}</dd><dt class="col-sm-5">Route</dt><dd class="col-sm-7">{{ str($form['route'])->title() }}</dd><dt class="col-sm-5">Wallet</dt><dd class="col-sm-7">{{ $selectedWallet->owner_type === 'organization' ? 'Organization SMS wallet' : 'My SMS wallet' }}</dd><dt class="col-sm-5">Source</dt><dd class="col-sm-7">{{ $audience['source_label'] }}</dd><dt class="col-sm-5">Scope</dt><dd class="col-sm-7">{{ $audience['scope_summary']['scope'] }}@if($audience['scope_summary']['locations']) · {{ collect($audience['scope_summary']['locations'])->map(fn($v,$k)=>$k.': '.$v)->join(', ') }}@endif</dd></dl></div>
        <div class="col-md-6"><dl class="row"><dt class="col-sm-6">Matched</dt><dd class="col-sm-6">{{ number_format($audience['matched']) }}</dd><dt class="col-sm-6">Valid/chargeable</dt><dd class="col-sm-6">{{ number_format($audience['valid']) }}</dd><dt class="col-sm-6">Invalid/skipped</dt><dd class="col-sm-6">{{ number_format($audience['invalid']) }}</dd><dt class="col-sm-6">Duplicates removed</dt><dd class="col-sm-6">{{ number_format($audience['duplicates']) }}</dd><dt class="col-sm-6">Message pages</dt><dd class="col-sm-6">{{ data_get($estimate, 'message_pages', '—') }}</dd><dt class="col-sm-6">Total units</dt><dd class="col-sm-6">{{ number_format((int) data_get($estimate, 'total_units', 0)) }}</dd><dt class="col-sm-6">Unit price</dt><dd class="col-sm-6">{{ data_get($estimate, 'currency', $selectedWallet->currency) }} {{ number_format((float) data_get($estimate, 'retail_price_per_unit', 0), 4) }}</dd><dt class="col-sm-6">Estimated total</dt><dd class="col-sm-6"><strong>{{ data_get($estimate, 'currency', $selectedWallet->currency) }} {{ number_format((float) data_get($estimate, 'estimated_total', 0), 2) }}</strong></dd><dt class="col-sm-6">Local available</dt><dd class="col-sm-6">{{ $selectedWallet->currency }} {{ number_format((float) $selectedWallet->available_balance, 2) }}</dd><dt class="col-sm-6">Portal master funding</dt><dd class="col-sm-6">{{ $confirmation['portal_affordable'] ? 'Available for estimate' : 'Insufficient' }}</dd></dl></div></div>
        @if($audience['valid'] >= $largeBatchWarning)<div class="alert alert-warning">This is a large send to {{ number_format($audience['valid']) }} recipients. Confirm the audience and message carefully.</div>@endif
        <div class="table-responsive"><table class="table table-sm"><thead><tr><th>Preview recipient</th><th>Name</th></tr></thead><tbody>@foreach($audience['preview'] as $row)<tr><td>{{ $row['phone'] }}</td><td>{{ $row['name'] ?? '—' }}</td></tr>@endforeach</tbody></table></div>
        <div class="alert alert-warning"><strong>Billing notice:</strong> delivery failures, rejection, expiry, undelivered status, or DND blocking do not automatically mean a refund. Local refunds are applied only from portal settlement evidence.</div>
        @if(!$confirmation['local_affordable'])<div class="alert alert-danger">@if($selectedWallet->owner_type === 'organization')The organization SMS wallet does not have enough available allocation. Ask an authorized administrator to fund or reallocate it.@elseThe selected local wallet does not have enough available balance. <a href="{{ route($profileData->access_level.'.sms.wallet') }}">Top up or request SMS credit</a>.@endif</div>@endif
        @if(!$confirmation['portal_affordable'])<div class="alert alert-danger">The portal installation master wallet cannot currently fund this batch. Contact an authorized campaign administrator.</div>@endif
        @if(!$confirmation['sending_enabled'])<div class="alert alert-danger">SMS sending is currently disabled in portal SMS settings.</div>@endif
        <h5>Message preview</h5><div class="border rounded p-3 mb-3" style="white-space:pre-wrap">{{ $form['message'] }}</div>
        <form method="POST" action="{{ route($profileData->access_level.'.sms.compose.send') }}">@csrf<input type="hidden" name="confirmation_token" value="{{ $confirmation['token'] }}"><button class="btn btn-success" @disabled(!$confirmation['can_send'])><i class="fas fa-check mr-1"></i> Confirm and submit SMS batch</button></form>
    </div></div>
    @endisset
</div></section>
<script>
document.addEventListener('DOMContentLoaded', function () {
    const source = document.getElementById('recipient-source'), filters = document.getElementById('database-filters'), manual = document.getElementById('manual-recipients'), agent = document.getElementById('agent-status-wrap');
    const toggleSource = () => { const isManual = source.value === 'manual'; filters.style.display = isManual ? 'none' : ''; manual.style.display = isManual ? '' : 'none'; agent.style.display = source.value === 'agents' ? '' : 'none'; };
    source.addEventListener('change', toggleSource); toggleSource();
    const message = document.getElementById('sms-message'), chars = document.getElementById('sms-char-count'), encoding = document.getElementById('sms-encoding'), pages = document.getElementById('sms-pages');
    const gsmBasic = "@£$¥èéùìòÇ\nØø\rÅåΔ_ΦΓΛΩΠΨΣΘΞÆæßÉ !\"#¤%&'()*+,-./0123456789:;<=>?¡ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÑÜ§¿abcdefghijklmnopqrstuvwxyzäöñüà";
    const gsmExtended = "^{}\\[~]|€\f";
    const updateMessage = () => { const value = message.value, symbols = Array.from(value), unicode = symbols.some(char => !gsmBasic.includes(char) && !gsmExtended.includes(char)), units = unicode ? value.length : symbols.reduce((total, char) => total + (gsmExtended.includes(char) ? 2 : 1), 0), single = unicode ? 70 : 160, multi = unicode ? 67 : 153; chars.textContent = value.length; encoding.textContent = unicode ? 'Unicode' : 'GSM-7'; pages.textContent = units <= single ? 1 : Math.ceil(units / multi); };
    message.addEventListener('input', updateMessage); updateMessage();
    const selects = { states: document.getElementById('sms-state'), lgas: document.getElementById('sms-lga'), wards: document.getElementById('sms-ward'), polling_units: document.getElementById('sms-pu') };
    const base = @json(route($profileData->access_level.'.sms.compose.locations', ['type' => '__TYPE__']));
    async function load(type, params = {}) { const select = selects[type], selected = select.dataset.selected; select.innerHTML = '<option value="">All permitted</option>'; const query = new URLSearchParams(params); const response = await fetch(base.replace('__TYPE__', type) + '?' + query.toString(), {headers:{'Accept':'application/json'}}); if (!response.ok) return; const payload = await response.json(); payload.data.forEach(row => { const option = new Option(row.name, row.id, false, String(row.id) === String(selected)); select.add(option); }); }
    async function initialLocations() { await load('states'); await load('lgas', {state_id: selects.states.value}); await load('wards', {lga_id: selects.lgas.value}); await load('polling_units', {ward_id: selects.wards.value}); }
    selects.states.addEventListener('change', async () => { selects.lgas.dataset.selected=''; selects.wards.dataset.selected=''; selects.polling_units.dataset.selected=''; await load('lgas',{state_id:selects.states.value}); await load('wards',{lga_id:''}); await load('polling_units',{ward_id:''}); });
    selects.lgas.addEventListener('change', async () => { selects.wards.dataset.selected=''; selects.polling_units.dataset.selected=''; await load('wards',{lga_id:selects.lgas.value}); await load('polling_units',{ward_id:''}); });
    selects.wards.addEventListener('change', async () => { selects.polling_units.dataset.selected=''; await load('polling_units',{ward_id:selects.wards.value}); });
    initialLocations();
});
</script>
@endsection
