@extends('backend.template.backend-master')
@section('content')
<section class="content"><div class="container-fluid">
    @php($smsSettings = \App\Models\SystemSetting::first())
    @php($smsAccess = app(\App\Services\Sms\SmsAccessService::class))
    @if($smsAccess->allows($profileData, 'sms.compose'))<p><a class="btn btn-primary" href="{{ route($profileData->access_level.'.sms.compose') }}"><i class="fas fa-paper-plane mr-1"></i> Compose SMS</a></p>@endif
    @if(session('payment_url'))<div class="alert alert-success">Payment is pending confirmation. <a class="btn btn-sm btn-success" href="{{ session('payment_url') }}" rel="noopener">Continue payment</a></div>@endif
    <div class="row"><div class="col-md-4"><div class="small-box bg-success"><div class="inner"><h3>{{ $wallet->currency }} {{ number_format((float)$wallet->available_balance, 2) }}</h3><p>Available balance</p></div></div></div><div class="col-md-4"><div class="small-box bg-info"><div class="inner"><h3>{{ number_format((float)$wallet->balance, 2) }}</h3><p>Allocated balance</p></div></div></div><div class="col-md-4"><div class="small-box bg-warning"><div class="inner"><h3>{{ number_format((float)$wallet->reserved_balance, 2) }}</h3><p>Reserved for batches</p></div></div></div></div>
    <div class="row"><div class="col-lg-6"><div class="card"><div class="card-header">Fund SMS wallet</div><div class="card-body">@if($smsSettings?->portal_sms_topup_enabled)<form method="POST" action="{{ route($profileData->access_level.'.sms.topups.store') }}">@csrf
        <div class="form-group"><label>Funding destination</label><select class="form-control" name="funding_type"><option value="user_wallet">Fund my SMS wallet</option>@if($organizationWallet)<option value="organization_wallet">Contribute to campaign SMS wallet</option>@endif</select></div>
        <div class="form-group"><label>Amount</label><input class="form-control" type="number" min="100" step="0.01" name="amount" required></div><div class="form-group"><label>Payment preference</label><select class="form-control" name="payment_method"><option value="paystack">Paystack, when available</option><option value="manual_bank">Manual bank payment</option></select><small class="text-muted">The portal selects an available configured method and may return manual instructions.</small></div><button class="btn btn-primary">Initiate top-up</button></form>@else<p class="text-muted">SMS top-ups are disabled.</p>@endif</div></div></div>
        <div class="col-lg-6"><div class="card"><div class="card-header">Request SMS credit</div><div class="card-body">@if($smsSettings?->portal_sms_credit_request_enabled)<form method="POST" action="{{ route($profileData->access_level.'.sms.credit-requests.store') }}">@csrf
            <div class="form-group"><label>Wallet</label><select class="form-control" name="wallet_type"><option value="user_wallet">My wallet</option>@if($organizationWallet)<option value="organization_wallet">Organization wallet</option>@endif</select></div><div class="form-group"><label>Amount</label><input class="form-control" type="number" min="1" step="0.01" name="amount" required></div><div class="form-group"><label>Reason</label><textarea class="form-control" name="reason" required></textarea></div><div class="form-group"><label>Urgency</label><select class="form-control" name="urgency"><option>normal</option><option>low</option><option>high</option><option>urgent</option></select></div><button class="btn btn-primary">Submit request</button></form>@else<p class="text-muted">SMS credit requests are disabled.</p>@endif
        </div></div></div></div>
    @if($wallet->owner_type === 'organization' && $smsAccess->allows($profileData, 'sms.wallet.transfer'))
    <div class="card"><div class="card-header">Local allocation administration</div><div class="card-body"><div class="row"><div class="col-lg-8"><form method="POST" action="{{ route($profileData->access_level.'.sms.transfers.store') }}">@csrf<div class="form-row"><div class="form-group col-md-3"><label>Direction</label><select class="form-control" name="direction"><option value="organization_to_user">Organization to user</option><option value="user_to_organization">User to organization</option></select></div><div class="form-group col-md-3"><label>User wallet owner</label><select class="form-control" name="user_id">@foreach($transferUsers as $user)<option value="{{ $user->id }}">{{ trim($user->firstname.' '.$user->lastname) }} ({{ $user->access_level }})</option>@endforeach</select></div><div class="form-group col-md-2"><label>Amount</label><input class="form-control" name="amount" type="number" min="0.0001" step="0.0001" required></div><div class="form-group col-md-4"><label>Reason</label><input class="form-control" name="reason" required></div></div><button class="btn btn-primary">Transfer local credit</button></form></div><div class="col-lg-4"><form method="POST" action="{{ route($profileData->access_level.'.sms.allocations.sync') }}">@csrf<button class="btn btn-outline-primary mt-4">Sync confirmed portal allocations</button></form></div></div></div></div>
    @endif
    <div class="card"><div class="card-header">Immutable wallet ledger</div><div class="card-body table-responsive"><table class="table table-bordered table-sm"><thead><tr><th>Date</th><th>Type</th><th>Direction</th><th>Amount</th><th>Balance after</th><th>Reference</th></tr></thead><tbody>@forelse($transactions as $row)<tr><td>{{ $row->created_at?->format('d M Y H:i') }}</td><td>{{ str($row->type)->replace('_',' ')->title() }}</td><td>{{ $row->direction }}</td><td>{{ number_format((float)$row->amount,2) }}</td><td>{{ number_format((float)$row->balance_after,2) }}</td><td><small>{{ $row->transaction_reference }}</small></td></tr>@empty<tr><td colspan="6" class="text-center text-muted">No wallet transactions.</td></tr>@endforelse</tbody></table>{{ $transactions->links() }}</div></div>
    <div class="row"><div class="col-lg-4"><div class="card"><div class="card-header">Top-up history</div><div class="card-body">@forelse($topups as $row)<p>{{ $row->currency }} {{ number_format((float)$row->amount,2) }} <span class="badge badge-secondary">{{ $row->status }}</span><br><small>{{ $row->created_at?->format('d M Y H:i') }}</small></p>@empty<p class="text-muted">No top-ups.</p>@endforelse</div></div></div><div class="col-lg-4"><div class="card"><div class="card-header">Allocation history</div><div class="card-body">@forelse($allocations as $row)<p>{{ $row->currency }} {{ number_format((float)$row->amount,2) }} <span class="badge badge-success">{{ $row->status }}</span><br><small>{{ $row->portal_reference }}</small></p>@empty<p class="text-muted">No allocations.</p>@endforelse</div></div></div><div class="col-lg-4"><div class="card"><div class="card-header">Credit requests</div><div class="card-body">@forelse($creditRequests as $row)<p>{{ $row->currency }} {{ number_format((float)$row->amount,2) }} <span class="badge badge-secondary">{{ $row->status }}</span><br><small>{{ \Illuminate\Support\Str::limit($row->reason, 70) }}</small></p>@empty<p class="text-muted">No credit requests.</p>@endforelse</div></div></div></div>
</div></section>
@endsection
