<?php

return [
    'packages' => [
        'presidential' => [
            'package_display_name' => 'Presidential Campaign',
            'dashboard_title' => 'National Campaign Dashboard',
            'statistics_title' => 'National Statistics',
            'election_statistics_title' => 'National Election Statistics',
            'geography_distribution_title' => 'Members Distribution by Geopolitical Region',
            'primary_geography_label' => 'Regions',
            'secondary_geography_labels' => ['States', 'LGAs', 'Wards', 'Polling Units'],
            'location_hierarchy_labels' => ['Regions', 'States', 'LGAs', 'Wards', 'Polling Units'],
            'dashboard_scope_title' => 'National Campaign',
            'charts' => [
                'gender' => 'Member Distribution by Gender',
                'age' => 'Member Distribution by Age Bracket',
                'region' => 'Members Distribution by Geopolitical Region',
                'geography' => 'Members Distribution by Geopolitical Region',
                'voter' => 'Member Distribution by Vote Eligibility',
                'religion' => 'Member Distribution by Religion',
                'state' => 'Member Distribution by States',
            ],
            'visible_charts' => ['gender', 'age', 'region', 'geography', 'voter', 'religion', 'state'],
        ],

        'governorship' => [
            'package_display_name' => 'Governorship Campaign',
            'dashboard_title' => 'State Campaign Dashboard',
            'statistics_title' => 'State Campaign Statistics',
            'election_statistics_title' => 'State Election Statistics',
            'geography_distribution_title' => 'Members Distribution by Local Government',
            'primary_geography_label' => 'LGAs',
            'secondary_geography_labels' => ['Senatorial Districts', 'Federal Constituencies', 'Wards', 'Polling Units'],
            'location_hierarchy_labels' => ['LGAs', 'Wards', 'Polling Units'],
            'dashboard_scope_title' => 'State Campaign',
            'charts' => [
                'gender' => 'Member Distribution by Gender',
                'age' => 'Member Distribution by Age Bracket',
                'geography' => 'Members Distribution by Local Government',
                'voter' => 'Member Distribution by Vote Eligibility',
                'religion' => 'Member Distribution by Religion',
                'state' => 'Members Distribution by Local Government',
            ],
            'visible_charts' => ['gender', 'age', 'geography', 'voter', 'religion'],
        ],

        'senatorial' => [
            'package_display_name' => 'Senatorial District Campaign',
            'dashboard_title' => 'Senatorial District Campaign Dashboard',
            'statistics_title' => 'Senatorial District Statistics',
            'election_statistics_title' => 'Senatorial District Election Statistics',
            'geography_distribution_title' => 'Members Distribution by LGA / Ward',
            'primary_geography_label' => 'LGAs',
            'secondary_geography_labels' => ['Wards', 'Polling Units'],
            'location_hierarchy_labels' => ['LGAs', 'Wards', 'Polling Units'],
            'dashboard_scope_title' => 'Senatorial District Campaign',
            'charts' => [
                'gender' => 'Member Distribution by Gender',
                'age' => 'Member Distribution by Age Bracket',
                'geography' => 'Members Distribution by LGA / Ward',
                'voter' => 'Member Distribution by Vote Eligibility',
                'religion' => 'Member Distribution by Religion',
                'state' => 'Members Distribution by LGA / Ward',
            ],
            'visible_charts' => ['gender', 'age', 'geography', 'voter', 'religion'],
        ],

        'federal_constituency' => [
            'package_display_name' => 'Federal Constituency Campaign',
            'dashboard_title' => 'Federal Constituency Campaign Dashboard',
            'statistics_title' => 'Federal Constituency Statistics',
            'election_statistics_title' => 'Federal Constituency Election Statistics',
            'geography_distribution_title' => 'Members Distribution by LGA / Ward',
            'primary_geography_label' => 'LGAs',
            'secondary_geography_labels' => ['Wards', 'Polling Units'],
            'location_hierarchy_labels' => ['LGAs', 'Wards', 'Polling Units'],
            'dashboard_scope_title' => 'Federal Constituency Campaign',
            'charts' => [
                'gender' => 'Member Distribution by Gender',
                'age' => 'Member Distribution by Age Bracket',
                'geography' => 'Members Distribution by LGA / Ward',
                'voter' => 'Member Distribution by Vote Eligibility',
                'religion' => 'Member Distribution by Religion',
                'state' => 'Members Distribution by LGA / Ward',
            ],
            'visible_charts' => ['gender', 'age', 'geography', 'voter', 'religion'],
        ],

        'chairmanship' => [
            'package_display_name' => 'Chairmanship Campaign',
            'dashboard_title' => 'Local Government Campaign Dashboard',
            'statistics_title' => 'LGA Campaign Statistics',
            'election_statistics_title' => 'LGA Election Statistics',
            'geography_distribution_title' => 'Members Distribution by Ward',
            'primary_geography_label' => 'Wards',
            'secondary_geography_labels' => ['Polling Units'],
            'location_hierarchy_labels' => ['Wards', 'Polling Units'],
            'dashboard_scope_title' => 'Local Government Campaign',
            'charts' => [
                'gender' => 'Member Distribution by Gender',
                'age' => 'Member Distribution by Age Bracket',
                'geography' => 'Members Distribution by Ward',
                'voter' => 'Member Distribution by Vote Eligibility',
                'religion' => 'Member Distribution by Religion',
                'state' => 'Members Distribution by Ward',
            ],
            'visible_charts' => ['gender', 'age', 'geography', 'voter'],
        ],

        'state_constituency' => [
            'package_display_name' => 'State Constituency Campaign',
            'dashboard_title' => 'Custom Campaign Dashboard',
            'statistics_title' => 'State Constituency Statistics',
            'election_statistics_title' => 'Election Statistics',
            'geography_distribution_title' => 'Members Distribution by Licensed Geography',
            'primary_geography_label' => 'Licensed Geography',
            'secondary_geography_labels' => ['Wards', 'Polling Units'],
            'location_hierarchy_labels' => ['Licensed Geography', 'Wards', 'Polling Units'],
            'dashboard_scope_title' => 'Custom Campaign',
            'charts' => [
                'gender' => 'Member Distribution by Gender',
                'age' => 'Member Distribution by Age Bracket',
                'geography' => 'Members Distribution by Licensed Geography',
                'voter' => 'Member Distribution by Vote Eligibility',
                'religion' => 'Member Distribution by Religion',
                'state' => 'Members Distribution by Licensed Geography',
            ],
            'visible_charts' => ['gender', 'age', 'geography', 'voter'],
        ],
    ],

    'breadcrumbs' => [
        'national' => 'National',
        'region' => 'Region',
        'state' => 'State',
        'senatorial_district' => 'Senatorial District',
        'federal_constituency' => 'Federal Constituency',
        'lga' => 'LGA',
        'ward' => 'Ward',
        'polling_unit' => 'Polling Unit',
    ],

    'card_groups' => [
        'coverage' => 'Coverage',
        'people' => 'People',
        'membership_activity' => 'Membership Activity',
        'election_operations' => 'Election Operations',
    ],
];
