<?php

return [
    'capabilities' => [
        'candidate' => [
            'dashboard.view',
            'reports.view',
            'elections.view',
            'community.view',
            'community.post.create',
            'community.post.edit_own',
            'community.post.delete_own',
            'community.comment.create',
            'community.comment.edit_own',
            'community.comment.delete_own',
            'community.media.upload',
        ],
        'campaign_director' => [
            'dashboard.view',
            'reports.view',
            'elections.view',
            'members.view',
            'agents.view',
            'community.view',
            'community.post.create',
            'community.post.edit_own',
            'community.post.delete_own',
            'community.comment.create',
            'community.comment.edit_own',
            'community.comment.delete_own',
            'community.media.upload',
        ],
        'coordinator' => [
            'dashboard.view',
            'reports.view',
            'members.view',
            'agents.view',
            'community.view',
            'community.post.create',
            'community.post.edit_own',
            'community.post.delete_own',
            'community.comment.create',
            'community.comment.edit_own',
            'community.comment.delete_own',
            'community.media.upload',
        ],
        'ict_director' => [
            'dashboard.view',
            'reports.view',
            'members.view',
            'members.create',
            'members.edit',
            'agents.view',
            'agents.approve',
            'settings.technical',
            'community.view',
            'community.post.create',
            'community.post.edit_own',
            'community.post.delete_own',
            'community.post.moderate',
            'community.comment.create',
            'community.comment.edit_own',
            'community.comment.delete_own',
            'community.comment.moderate',
            'community.media.upload',
            'community.media.video_upload',
            'community.settings.manage',
        ],
        'agent' => [
            'dashboard.view',
            'results.submit',
            'incidents.manage',
            'community.view',
            'community.post.create',
            'community.post.edit_own',
            'community.post.delete_own',
            'community.comment.create',
            'community.comment.edit_own',
            'community.comment.delete_own',
        ],
        'member' => [
            'dashboard.view',
            'community.view',
            'community.post.create',
            'community.post.edit_own',
            'community.post.delete_own',
            'community.comment.create',
            'community.comment.edit_own',
            'community.comment.delete_own',
            'community.media.upload',
        ],
        'superadmin' => [
            '*',
        ],
    ],

    'role_capability_groups' => [
        'Super Admin' => 'superadmin',
        'Member' => 'member',

        'Presidential Candidate' => 'candidate',
        'Vice Presidential Candidate' => 'candidate',
        'Governorship Candidate' => 'candidate',
        'Deputy Governorship Candidate' => 'candidate',
        'Senatorial Candidate' => 'candidate',
        'Federal Constituency Candidate' => 'candidate',
        'Chairmanship Candidate' => 'candidate',
        'Deputy Chairmanship Candidate' => 'candidate',
        'State Constituency Candidate' => 'candidate',

        'National Campaign Director' => 'campaign_director',
        'State Campaign Director' => 'campaign_director',
        'Senatorial Campaign Director' => 'campaign_director',
        'Federal Constituency Campaign Director' => 'campaign_director',
        'LGA Campaign Director' => 'campaign_director',
        'State Constituency Campaign Director' => 'campaign_director',

        'National Coordinator' => 'coordinator',
        'Regional Coordinator' => 'coordinator',
        'State Coordinator' => 'coordinator',
        'Senatorial Coordinator' => 'coordinator',
        'Senatorial District Coordinator' => 'coordinator',
        'Federal Constituency Coordinator' => 'coordinator',
        'LGA Coordinator' => 'coordinator',
        'Ward Coordinator' => 'coordinator',

        'National ICT Director' => 'ict_director',
        'Regional ICT Director' => 'ict_director',
        'State ICT Director' => 'ict_director',
        'Senatorial ICT Director' => 'ict_director',
        'Federal Constituency ICT Director' => 'ict_director',
        'Federal ICT Director' => 'ict_director',
        'LGA ICT Director' => 'ict_director',
        'Ward ICT Director' => 'ict_director',
        'PU ICT Director' => 'ict_director',

        'Polling Unit Agent' => 'agent',
        'PU Agent' => 'agent',
    ],
];
