<?php

return [
    'identity' => [
        'name' => 'Campaign Manager Core',
        'package' => 'campaign-manager-core',
        'channel' => env('RELEASE_CHANNEL', 'self-hosted'),
        'version' => env('APP_VERSION', '1.0.5'),
        'build_date' => env('RELEASE_BUILD_DATE', null),
        'minimum_php' => '8.2.0',
    ],

    'release_notes' => [
        '1.0.9' => [
            'Installer geography selection now preserves authoritative Portal geography codes separately from Portal IDs.',
            'Base campaign geography bootstrapping creates or reuses coded State, Senatorial District, Federal Constituency, and LGA records.',
            'QuickStart provisioning reuses matching null-code local geography records instead of creating duplicate coded parents.',
            'Local campaign settings and LocalLicense scope IDs are synchronized to canonical local geography IDs after provisioning.',
            'A repair command reconciles existing duplicate geography caused by prior null-code installer records.',
        ],
        '1.0.8' => [
            'QuickStart installation no longer incorrectly requires a legacy activation reference when the provisioning entitlement has activation_required=false.',
            'QuickStart now proceeds directly to geography provisioning after entitlement validation.',
            'New Community/QuickStart users no longer receive legacy software-activation errors in this path.',
        ],
        '1.0.2' => [
            'Email Notifications with access-level communication permissions.',
            'Branded email composition, preview, queued delivery, and recipient status tracking.',
            'Jurisdiction-first recipient targeting with package-aware audience filters.',
            'Secure notification details and recipient delivery reports.',
            'Shared-hosting installation guidance for a public-directory symbolic link.',
            'Safe .htaccess.example template; real server .htaccess files are excluded.',
        ],
        '1.0.3' => [
            'Cumulative corrective release for issues identified after v1.0.2 across authentication, onboarding, routing, installer behavior, licensed scope, member facilities, announcements, elections, and messaging.',
            'Licensed location scopes are reconciled to local IDs before installation completes.',
            'Installer mail settings are persisted as the active runtime mail configuration.',
            'Member access now fails closed for inactive accounts and missing geographic scope.',
            'Authentication, registration, onboarding, and account routes now use access-level namespaces with centralized route resolution.',
            'Election and polling-unit agent endpoints enforce licensed module availability.',
            'Member routes and navigation now share an executable product capability contract.',
            'Legacy member administration and campaign-management screens are removed from ordinary member accounts.',
            'Member profiles enforce licensed location lineage, unique email addresses, and stronger password rules.',
            'Member navigation follows the licensed campaign geography hierarchy.',
            'Member voting blocs and direct referrals provide cycle-safe multi-level reporting.',
            'The superadmin Public Registration switch controls member voting-bloc and referral availability.',
            'A full jurisdiction-aware Announcement and Notice Board module provides manager permissions, scheduled publication, expiry, dashboard notices, member listing, and detail views.',
            'Notice URLs use UUID route binding inside each authenticated access-level namespace.',
            'Approved polling-unit agents receive a scoped election workspace for results and incident reporting.',
            'Internal messaging now loads, sends, marks read, and reports typing through the correct access-level route namespace.',
            'Message and reply bodies consistently persist and render through the messages.body contract.',
            'Messaging initiation, recipient discovery, thread visibility, and reply authorization share one hierarchy-aware scoped policy.',
            'Same-level and downward messaging respects package and location scope; upward replies require an established thread context.',
        ],
        '1.0.4' => [
            'Portal-backed SMS module with signed API authentication, connection diagnostics, sender IDs, audience estimates, batch sending, delivery reporting, and settlement synchronization.',
            'User and campaign SMS wallets support top-ups, credit requests, local allocations, reservations, immutable transaction history, and role-aware access controls.',
            'SMS navigation is available to eligible campaign administrators and remains governed by the licensed SMS module entitlement.',
            'Portal SMS endpoint resolution now supports the contract operation keys used by wallet, sender ID, batch, allocation, top-up, and credit-request APIs.',
            'Release-facing role, license, community, email, and SMS screens no longer expose internal implementation notices.',
            'Campaign audience and election scope labels now use package-neutral Campaignwide wording or the resolved licensed campaign scope instead of Nationwide defaults.',
        ],
        '1.0.5' => [
            'SMS wallet transaction and audit polymorphic indexes now install on MySQL servers with a 1000-byte maximum index-key limit.',
        ],
    ],

    'signing' => [
        'keys_dir' => env('CAMPAIGN_RELEASE_KEYS_DIR', 'storage/app/release-keys'),
        'private_key_path' => env('CAMPAIGN_RELEASE_PRIVATE_KEY_PATH', 'storage/app/release-keys/campaign_release_private.pem'),
        'public_key_path' => env('CAMPAIGN_RELEASE_PUBLIC_KEY_PATH', 'storage/app/release-keys/campaign_release_public.pem'),
        'public_key' => env('RELEASE_SIGNING_PUBLIC_KEY'),
        'public_key_id' => env('RELEASE_SIGNING_PUBLIC_KEY_ID', 'campaign-manager-release-v1'),
    ],

    'github' => [
        'repository' => env('CAMPAIGN_RELEASE_GITHUB_REPO', 'joshualion/Campaign-Manager'),
        'allowed_repositories' => array_filter(array_map(
            'trim',
            explode(',', env('CAMPAIGN_RELEASE_ALLOWED_GITHUB_REPOS', 'joshualion/Campaign-Manager'))
        )),
        'last_released_version' => env('CAMPAIGN_RELEASE_LAST_VERSION', '1.0.6'),
        'version_state_path' => env('CAMPAIGN_RELEASE_VERSION_STATE_PATH', 'release-state.json'),
    ],

    'protected_file_patterns' => [
        'app/Services/*License*.php',
        'app/Services/*Activation*.php',
        'app/Services/*Portal*.php',
        'app/Services/*Provisioning*.php',
        'app/Services/RemoteLicenseClient.php',
        'app/Services/LocalLicenseService.php',
        'app/Services/LocationProvisioningClient.php',
        'app/Services/LocationProvisioningImportService.php',
        'app/Services/Installer/*.php',
        'app/Http/Controllers/InstallerController.php',
        'app/Http/Middleware/*License*.php',
        'app/Console/Commands/Campaign*License*.php',
        'app/Console/Commands/Campaign*Provision*.php',
        'app/Console/Commands/CampaignLocationsProvision.php',
        'app/Console/Commands/CampaignRelease.php',
        'app/Console/Commands/CampaignIntegrityCheck.php',
        'config/campaign.php',
        'config/release.php',
        'routes/install.php',
    ],

    'harden_php_patterns' => [
        'app/Services/*License*.php',
        'app/Services/*Activation*.php',
        'app/Services/*Portal*.php',
        'app/Services/*Provisioning*.php',
        'app/Services/RemoteLicenseClient.php',
        'app/Services/LocalLicenseService.php',
        'app/Services/LocationProvisioningClient.php',
        'app/Services/LocationProvisioningImportService.php',
        'app/Services/Installer/*.php',
        'app/Http/Controllers/InstallerController.php',
        'app/Http/Middleware/*License*.php',
        'app/Console/Commands/Campaign*License*.php',
        'app/Console/Commands/Campaign*Provision*.php',
        'app/Console/Commands/CampaignLocationsProvision.php',
        'app/Console/Commands/CampaignRelease.php',
    ],

    'harden_php_max_bytes' => 262144,

    'default_output' => 'builds/releases',

    'profiles' => [
        'standard' => [
            'label' => 'Campaign Manager',
            'filename' => 'campaign-manager.zip',
            'manifest_filename' => 'campaign-manager-v{version}.json',
            'includes_full_location_data' => false,
            'includes_bootstrap_location_data' => true,
            'automatic_location_provisioning' => false,
            'location_data_roots' => [
                'storage/app/imports/campaign-locations/bootstrap',
            ],
            'required_location_csvs' => [
                'storage/app/imports/campaign-locations/bootstrap/states.csv',
                'storage/app/imports/campaign-locations/bootstrap/senatorial_districts.csv',
                'storage/app/imports/campaign-locations/bootstrap/federal_constituencies.csv',
                'storage/app/imports/campaign-locations/bootstrap/local_government_areas.csv',
                'storage/app/imports/campaign-locations/bootstrap/wards.csv',
                'storage/app/imports/campaign-locations/bootstrap/polling_units.csv',
            ],
            'expected_location_records' => [
                'regions' => 6,
                'states' => 37,
                'senatorial_districts' => 109,
                'federal_constituencies' => 360,
                'lgas' => 774,
                'wards' => 8809,
                'polling_units' => 176846,
            ],
        ],
        'full' => [
            'label' => 'Campaign Manager Self-Hosted Portal Provisioned',
            'filename' => 'campaign-manager-self-hosted-portal-provisioned-v{version}.zip',
            'manifest_filename' => 'campaign-manager-self-hosted-portal-provisioned-v{version}.json',
            'includes_full_location_data' => false,
            'includes_bootstrap_location_data' => true,
            'automatic_location_provisioning' => true,
            'location_data_roots' => [
                'storage/app/imports/campaign-locations/bootstrap',
            ],
            'required_location_csvs' => [
                'storage/app/imports/campaign-locations/bootstrap/states.csv',
                'storage/app/imports/campaign-locations/bootstrap/senatorial_districts.csv',
                'storage/app/imports/campaign-locations/bootstrap/federal_constituencies.csv',
                'storage/app/imports/campaign-locations/bootstrap/local_government_areas.csv',
                'storage/app/imports/campaign-locations/bootstrap/wards.csv',
                'storage/app/imports/campaign-locations/bootstrap/polling_units.csv',
            ],
            'expected_location_records' => [
                'regions' => 6,
                'states' => 37,
                'senatorial_districts' => 109,
                'federal_constituencies' => 360,
                'lgas' => 774,
                'wards' => 8809,
                'polling_units' => 176846,
            ],
        ],
        'community' => [
            'label' => 'Campaign Manager Community Bootstrap',
            'filename' => 'campaign-manager-community-bootstrap-v{version}.zip',
            'manifest_filename' => 'campaign-manager-community-bootstrap-v{version}.json',
            'includes_full_location_data' => false,
            'includes_bootstrap_location_data' => true,
            'automatic_location_provisioning' => false,
            'location_data_roots' => [
                'storage/app/imports/campaign-locations/bootstrap',
            ],
            'required_location_csvs' => [
                'storage/app/imports/campaign-locations/bootstrap/states.csv',
                'storage/app/imports/campaign-locations/bootstrap/senatorial_districts.csv',
                'storage/app/imports/campaign-locations/bootstrap/federal_constituencies.csv',
                'storage/app/imports/campaign-locations/bootstrap/local_government_areas.csv',
                'storage/app/imports/campaign-locations/bootstrap/wards.csv',
                'storage/app/imports/campaign-locations/bootstrap/polling_units.csv',
            ],
            'expected_location_records' => [
                'regions' => 1,
                'states' => 1,
                'senatorial_districts' => 1,
                'federal_constituencies' => 1,
                'lgas' => 1,
                'wards' => 1,
                'polling_units' => 1,
            ],
        ],
    ],

    'required_files' => [
        'artisan',
        'composer.json',
        'composer.lock',
        'vendor/autoload.php',
        'public/index.php',
        'public/.htaccess',
        '.htaccess.example',
        'public/build/manifest.json',
        '.env.example',
        '.env.production.example',
        'README-SELF-HOSTED.md',
        'CHANGELOG.md',
        'LICENSE.txt',
        'EULA.txt',
        'docs/self-hosted-installation-guide.md',
        'docs/self-hosted-shared-hosting-guide.md',
        'docs/member-product-contract.md',
        'app/Events/MessageSent.php',
        'app/Events/MessageTyping.php',
        'app/Http/Controllers/AjaxController.php',
        'app/Http/Controllers/Auth/AuthenticatedSessionController.php',
        'app/Http/Controllers/ElectionController.php',
        'app/Http/Controllers/InstallerController.php',
        'app/Http/Controllers/MessageController.php',
        'app/Http/Controllers/ProfileCompletionController.php',
        'app/Http/Controllers/UserController.php',
        'app/Http/Controllers/EmailNotificationController.php',
        'app/Http/Controllers/Auth/RegisteredUserController.php',
        'app/Http/Controllers/AnnouncementController.php',
        'app/Http/Controllers/MemberElectionController.php',
        'app/Http/Controllers/SmsController.php',
        'app/Http/Controllers/SmsComposeController.php',
        'app/Http/Controllers/SmsReportController.php',
        'app/Http/Controllers/SmsSettingsController.php',
        'app/Http/Controllers/superadmin/EmailNotificationPermissionController.php',
        'app/Http/Middleware/EnsureEmailNotificationsEnabled.php',
        'app/Http/Middleware/EnsureActiveUser.php',
        'app/Http/Middleware/EnsureModuleEnabled.php',
        'app/Http/Middleware/EnsureMemberCapability.php',
        'app/Http/Middleware/EnsurePublicRegistrationEnabled.php',
        'app/Http/Middleware/EnsureAnnouncementManager.php',
        'app/Http/Middleware/EnsureElectionReportAccess.php',
        'app/Http/Middleware/EnsureSmsAccess.php',
        'app/Jobs/SendEmailNotificationCampaignJob.php',
        'app/Jobs/SyncPortalSmsAllocations.php',
        'app/Jobs/SyncPortalSmsBatch.php',
        'app/Mail/CampaignEmailNotification.php',
        'app/Models/EmailNotificationCampaign.php',
        'app/Models/EmailNotificationPermission.php',
        'app/Models/EmailNotificationRecipient.php',
        'app/Models/SystemSetting.php',
        'app/Models/SmsAllocation.php',
        'app/Models/SmsAuditLog.php',
        'app/Models/SmsBatch.php',
        'app/Models/SmsCreditRequest.php',
        'app/Models/SmsMessage.php',
        'app/Models/SmsSenderId.php',
        'app/Models/SmsStatusEvent.php',
        'app/Models/SmsTopup.php',
        'app/Models/SmsWallet.php',
        'app/Models/SmsWalletReservation.php',
        'app/Models/SmsWalletTransaction.php',
        'app/Models/Announcement.php',
        'app/Models/Conversation.php',
        'app/Models/Message.php',
        'app/Models/User.php',
        'app/Services/AccessLevelRouteService.php',
        'app/Services/CampaignPackageUiService.php',
        'app/Services/EmailNotificationAudienceService.php',
        'app/Services/EmailNotificationPermissionService.php',
        'app/Services/Installer/InstallerMailSettingsService.php',
        'app/Services/Installer/InstallerService.php',
        'app/Services/Installer/BaseCampaignGeographyBootstrapper.php',
        'app/Services/Installer/CampaignGeographyDirectoryClient.php',
        'app/Http/Controllers/InstallerController.php',
        'app/Services/LocationProvisioningImportService.php',
        'app/Services/LocationProvisioningIntegrityService.php',
        'app/Services/LocationScopeService.php',
        'app/Services/CampaignInstallationSettingsService.php',
        'app/Services/GeographyIdentityRepairService.php',
        'app/Services/MemberCapabilityService.php',
        'app/Services/MemberVotingBlocService.php',
        'app/Services/PublicRegistrationService.php',
        'app/Services/AnnouncementAudienceService.php',
        'app/Services/MemberElectionParticipationService.php',
        'app/Services/LocationSelectionValidationService.php',
        'app/Services/ScopedMessagingRecipientService.php',
        'app/Services/Sms/PortalSmsClient.php',
        'app/Services/Sms/SmsAccessService.php',
        'app/Services/Sms/SmsAllocationSyncService.php',
        'app/Services/Sms/SmsAuditService.php',
        'app/Services/Sms/SmsBatchService.php',
        'app/Services/Sms/SmsPhoneNormalizer.php',
        'app/Services/Sms/SmsRecipientService.php',
        'app/Services/Sms/SmsReportAccessService.php',
        'app/Services/Sms/SmsSettlementSyncService.php',
        'app/Services/Sms/SmsWalletService.php',
        'app/Support/SmsMoney.php',
        'app/Services/PackageGovernanceService.php',
        'app/Services/LocalLicenseScopeReconciliationService.php',
        'app/Services/GitHubReleasePublisher.php',
        'app/Services/ReleaseVersionState.php',
        'app/Console/Commands/CampaignRelease.php',
        'app/Console/Commands/CampaignRepairGeographyIdentity.php',
        'app/Providers/AppServiceProvider.php',
        'bootstrap/app.php',
        'config/mail.php',
        'config/campaign.php',
        'config/member_access.php',
        'config/portal_sms.php',
        'database/migrations/2026_07_01_000001_create_email_notification_tables.php',
        'database/migrations/2025_12_24_000100_create_conversations_table.php',
        'database/migrations/2025_12_24_000110_create_conversation_participants_table.php',
        'database/migrations/2025_12_24_000120_create_messages_table.php',
        'database/migrations/2026_07_03_000001_complete_announcements_notice_board.php',
        'database/migrations/2026_07_03_000002_add_uuid_to_announcements.php',
        'database/migrations/2026_07_04_000001_create_portal_sms_core_tables.php',
        'database/migrations/2026_07_05_000001_finalize_portal_sms_staging_contract.php',
        'database/migrations/2026_09_06_000001_add_boundary_inec_codes_to_location_tables.php',
        'database/seeders/SMTPSettingsSeeder.php',
        'resources/views/backend/email-notifications/index.blade.php',
        'resources/js/app.js',
        'resources/js/components/MessengerWidget.vue',
        'resources/js/components/NewConversation.vue',
        'resources/js/components/SendMessage.vue',
        'resources/views/backend/messages.blade.php',
        'resources/views/backend/email-notifications/create.blade.php',
        'resources/views/backend/email-notifications/preview.blade.php',
        'resources/views/backend/email-notifications/show.blade.php',
        'resources/views/backend/email-notifications/partials/composition-fields.blade.php',
        'resources/views/backend/superadmin/settings/email-notifications/permissions.blade.php',
        'resources/views/emails/campaign-notification.blade.php',
        'resources/views/backend/template/partials/email-notifications-menu-item.blade.php',
        'resources/views/backend/template/federalAdminMenu.blade.php',
        'resources/views/backend/template/lgaAdminMenu.blade.php',
        'resources/views/backend/template/nationalAdminMenu.blade.php',
        'resources/views/backend/template/puAdminMenu.blade.php',
        'resources/views/backend/template/regionalAdminMenu.blade.php',
        'resources/views/backend/template/senatorialAdminMenu.blade.php',
        'resources/views/backend/template/stateAdminMenu.blade.php',
        'resources/views/backend/template/superadminmenu.blade.php',
        'resources/views/backend/template/wardAdminMenu.blade.php',
        'resources/views/backend/template/userMenu.blade.php',
        'resources/views/backend/user/profile.blade.php',
        'resources/views/backend/user/change_password.blade.php',
        'resources/views/backend/user/referrals.blade.php',
        'resources/views/backend/user/voting-block.blade.php',
        'resources/views/backend/user/notice-board.blade.php',
        'resources/views/backend/user/notice-show.blade.php',
        'resources/views/backend/user/election/index.blade.php',
        'resources/views/backend/user/election/results.blade.php',
        'resources/views/backend/user/election/workspace.blade.php',
        'resources/views/backend/user/election/submit-result.blade.php',
        'resources/views/backend/user/election/report-incident.blade.php',
        'resources/views/backend/announcements/index.blade.php',
        'resources/views/backend/announcements/create.blade.php',
        'resources/views/backend/announcements/edit.blade.php',
        'resources/views/backend/announcements/partials/form.blade.php',
        'resources/views/backend/template/partials/announcements-menu-item.blade.php',
        'resources/views/backend/superadmin/settings/system/frontend_community.blade.php',
        'resources/views/backend/sms/dashboard.blade.php',
        'resources/views/backend/sms/compose.blade.php',
        'resources/views/backend/sms/wallet.blade.php',
        'resources/views/backend/sms/sender-ids.blade.php',
        'resources/views/backend/sms/batches.blade.php',
        'resources/views/backend/sms/batch.blade.php',
        'resources/views/backend/sms/settings.blade.php',
        'resources/views/backend/template/partials/sms-menu.blade.php',
        'resources/views/backend/template/navbar.blade.php',
        'resources/views/backend/template/sidebar.blade.php',
        'resources/views/backend/user/dashboard.blade.php',
        'resources/views/frontend/layouts/app.blade.php',
        'resources/views/frontend/messages.blade.php',
        'resources/views/frontend/partials/campaign-manager-bootstrap.blade.php',
        'resources/views/frontend/profileFeed.blade.php',
        'resources/views/frontend/sidebar.blade.php',
        'resources/views/frontend/topnav.blade.php',
        'resources/views/frontend/viewUserProfileFeed.blade.php',
        'resources/views/installer/step.blade.php',
        'resources/views/welcome.blade.php',
        'routes/memberAdmin.php',
        'routes/auth.php',
        'routes/install.php',
        'routes/superAdmin.php',
        'routes/web.php',
        'storage/logs/.gitkeep',
    ],

    'required_location_csvs' => [
        'storage/app/imports/campaign-locations/bootstrap/states.csv',
        'storage/app/imports/campaign-locations/bootstrap/senatorial_districts.csv',
        'storage/app/imports/campaign-locations/bootstrap/federal_constituencies.csv',
        'storage/app/imports/campaign-locations/bootstrap/local_government_areas.csv',
        'storage/app/imports/campaign-locations/bootstrap/wards.csv',
        'storage/app/imports/campaign-locations/bootstrap/polling_units.csv',
    ],

    'writable_directories' => [
        'storage/framework/cache',
        'storage/framework/sessions',
        'storage/framework/views',
        'storage/logs',
        'bootstrap/cache',
        'public/uploads',
        'public/uploads/community/photos',
        'public/uploads/community/videos',
        'public/uploads/member_images',
        'public/uploads/system_images/election_result_sheets',
    ],

    'include_roots' => [
        'app',
        'bootstrap',
        'config',
        'database',
        'docs',
        'public',
        'resources',
        'routes',
        'vendor',
        'artisan',
        'composer.json',
        'composer.lock',
        'package.json',
        'vite.config.js',
        '.env.example',
        '.env.production.example',
        'README-SELF-HOSTED.md',
        'CHANGELOG.md',
        'LICENSE.txt',
        'EULA.txt',
        '.htaccess.example',
        'storage/logs/.gitkeep',
    ],

    'exclude_patterns' => [
        '.env',
        '.env.*',
        '!.env.example',
        '!.env.production.example',
        '.git',
        '.github',
        '.agents',
        '.codex',
        'docs/*',
        '!docs/self-hosted-installation-guide.md',
        '!docs/self-hosted-shared-hosting-guide.md',
        '!docs/member-product-contract.md',
        '.htaccess',
        '!public/.htaccess',
        'htaccess',
        'node_modules',
        'tests',
        'storage/app/installed.lock',
        'storage/app/release-keys/*',
        '!storage/app/release-keys/.gitkeep',
        'storage/app/private/*',
        'storage/app/private/campaign-manager/releases/*.zip',
        'storage/app/private/releases/archive/*.zip',
        'storage/app/imports/*/prepared/all/*',
        'storage/app/imports/*/prepared/all/**',
        'storage/app/imports/*/full/*',
        'storage/app/imports/*/full-data/*',
        'storage/app/imports/campaign-locations/prepared/all/*',
        'storage/app/imports/campaign-locations/prepared/all/**',
        'storage/app/imports/inec/prepared/all/*',
        'storage/app/imports/inec/prepared/all/**',
        'storage/app/public/uploads/*',
        'storage/app/releases/*',
        'storage/logs/*',
        'storage/logs/**',
        '!storage/logs/.gitkeep',
        'storage/framework/cache/*',
        'storage/framework/sessions/*',
        'storage/framework/views/*',
        'storage/framework/testing/*',
        'bootstrap/cache/*.php',
        'bootstrap/cache/*.tmp',
        'public/hot',
        'public/releases/*',
        'public/storage',
        'public/uploads/community/photos/*',
        '!public/uploads/community/photos/.gitkeep',
        'public/uploads/community/videos/*',
        '!public/uploads/community/videos/.gitkeep',
        'public/uploads/member_images/*',
        '!public/uploads/member_images/.gitkeep',
        'public/uploads/product_images/*',
        'public/uploads/logo/*',
        'public/uploads/system_images/*',
        '!public/uploads/system_images/politicalparty/*',
        '!public/uploads/system_images/politicalparty/**',
        'public/uploads/system_images/election_result_sheets/*',
        '!public/uploads/system_images/election_result_sheets/.gitkeep',
        'public/uploads/uploads/*',
        'database/database.sqlite',
        '*.sql',
        '*.sql.gz',
        '*.dump',
        '*.sqlite',
        '*.sqlite3',
        '*.bak',
        'node_modules/**',
        'vendor/.cache/*',
        'vendor/.cache/**',
        '*.zip',
        'builds/*',
        'release-manifest.json',
        '*-build-report.json',
        'vite.config.js.timestamp-*.mjs',
        '.phpunit.cache',
        '.phpunit.result.cache',
        '.pest',
        '.idea',
        '.vscode',
        '.DS_Store',
        'Thumbs.db',
    ],
];
